### ISSUE TITLE
Set up staging deploy to Netlify

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/argo-astro#1]

**Comment by garrettdashnelson** [comment]
@alexandergknoll  This is now set up, and Netlify will deploy https://argo-astro-dev.netlify.app with every commit to the `main` branch. In order to make the builds work successfully, I had to make some of the dummy routing pages which previously were just blank files into actual operable routes with `getStaticPaths()`, but I didn't do much beyond that.

**Comment by alexandergknoll** [comment]
Thanks a bunch @garrettdashnelson !  Sorry for the radio silence over here.  I'll try to get back with you on some of these before EOD tomorrow.

alex
