### ISSUE TITLE
Map base layer of "Search by map" module broken

### ISSUE THREAD

**Issue by emilyrbowe** [bplmaps/argo-astro#112]
Just had a call with Ala + Henry and Ala flagged that the map base layer isn't working as expected (see below for screenshot):

![image](https://github.com/user-attachments/assets/230695d0-1a71-46c5-9fb2-1822540627d1)

@garrettdashnelson, I'll leave decision-making/delegating to you on this one, but wanted to flag it since I just had the call.

**Comment by alexandergknoll** [comment]
@emilyrbowe @garrettdashnelson looks to me like it may have something to do with the maptiler.com API (cuplrit looks like the call to apply the styles on line 98 of `src/components/SearchByMap/SearchByMap.astro`

Maybe log in and check to make sure the API key is still valid and the payment method isn't expired etc.
