### ISSUE TITLE
Wireframe collection record page type

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/argo-astro#4]
This is the key collection-record page type, which I currently have routed at `src/pages/maps/[identifier].astro`.

It should mimic the functionality of the existing codebase's `pages/maps/_solr_id.vue` route, which renders in deployment as (e.g.) https://www.argomaps.org/maps/commonwealth:q524n7308/

The content should populate by traversing the JSON files in the `src/content/maps` directory.

Huge caveat here: for milestone 1, let's actually *leave the IIIF viewer component entirely blank*—it can just load the Manifest URI into a div or something like that. The reason for that is that the existing codebase loads the [Tify](https://tify.rocks) library client-side. I would like to migrate over to using the React-based [Clover](https://samvera-labs.github.io/clover-iiif/) and including it in the build chain as an Astro island, but right now we've been having trouble using Clover with Manifest URIs that have redirects in them.

**Comment by garrettdashnelson** [comment]
@alexandergknoll I'm reopening this issue and noting the comment I posted in this PR, which I probably should have posted here instead:

https://github.com/bplmaps/argo-astro/pull/9#issuecomment-1781326387

Basically, I'd like the "Tags" section to populate with data derived from the facets, but I'm not sure whether the build will be performant if it needs to traverse the facet data set, or whether I should pre-compile tags into the collection record `argoMetadata` field.

**Comment by alexandergknoll** [comment]
@garrettdashnelson opened a new PR to address that!

https://github.com/bplmaps/argo-astro/pull/16

**Comment by garrettdashnelson** [comment]
Closed by #16
