### ISSUE TITLE
Migrate thumbnails and descriptions from old ARGO site

### ISSUE THREAD

**Issue by almontg** [bplmaps/argo-astro#40]
Can fix now:

- Thumbnail Images for Empires & Nations, Mapping the Revolution
- Descriptive Text for George Washington Maps
- Fix link for Mapping the Revolution on homepage

Need to create additional information:

- Descriptive Text for all Themes (Empires & Nations, Features, Languages, & Subjects)
- Descriptive Text for Forgotten Theater
- Thumbnail Images for certain Themes (Features, Languages, Subjects)

**Comment by hkemp2128** [comment]
I have gone through and updated thumbnails for all Themes, as well as migrated descriptive text for GW maps and fixed the Mapping Revolution link. Not sure what the best course of action is on the Mapping the Rev thumbnail image is; it seems like the old image is not from a map and stored directly in the site files, and we don't seem to have a static images folder on the new site for me to bring an image over. I can link it to the old site image for now so we have a placeholder, but that's not a long-term solution.

I'll continue with creating content for the missing descriptive text under Themes in the meantime.
