### ISSUE TITLE
Migrate content from people pages

### ISSUE THREAD

**Issue by almontg** [bplmaps/argo-astro#42]
Headers and thumbnails can be done right away. Need to have a discussion re: styling, footnotes, displaying related maps etc.  before bringing over actual content.

**Comment by hkemp2128** [comment]
Updated banner images for 26 people with IIIF manifest crop URLs. Listed below are the 10 people that still need banner image updates, as the current images don't have digital collections entries/IIIF manifests to link (to my knowledge, please correct me if I am wrong). If I understand the code layout correctly, simply updating the banner_image variable under src/content/people seems to change both the thumbnail image and the header image of their individual page, but let me know if there's a place on the site I need to update additionally with IIIF URLs.

Header Image URLs still link to old site (10 total of 36):
- Charles Blaskowitz
- Elizabeth Simcoe
- Henry Pelham
- Jean Baptiste Bourguignon d’Anville
- John Graves Simcoe
- John Montresor
- Joseph Frederick Wallet DesBarres
- Pierre Charles L’Enfant
- Samuel Holland
- Simeon De Witt

**Comment by almontg** [comment]
Keeping this open for now, will use to track adding in the new people from the last batch we got from Denver Brunsman
