### ISSUE TITLE
Hosting static images

### ISSUE THREAD

**Issue by almontg** [bplmaps/argo-astro#43]
Need to discuss how best to host, as several pages use non-map images and this will be an ongoing issue

**Comment by hkemp2128** [comment]
Just adding a comment here so we have information collected in one place; right now we know we need to bring over static image thumbnails for the Mapping the Revolution section, as well as the following ten people: 

- Charles Blaskowitz
- Elizabeth Simcoe
- Henry Pelham
- Jean Baptiste Bourguignon d’Anville
- John Graves Simcoe
- John Montresor
- Joseph Frederick Wallet DesBarres
- Pierre Charles L’Enfant
- Samuel Holland
- Simeon De Witt

**Comment by hkemp2128** [comment]
Adding onto above comment, there are also static images in the bios for Mary Ann Rocque and Elizabeth Simcoe that have filepaths copied over from old CMS leading to an old static image file that no longer exists, will need fixing

**Comment by garrettdashnelson** [comment]
@hkemp2128 when you have done some experimenting with uploading static content into the Storyblok assets module, and then linking to them in the appropriate places in the ARGO content data sources, let us know what you think—and whether we can close this issue, at least for now.

**Comment by hkemp2128** [comment]
@garrettdashnelson I have uploaded images to Storyblok for all the locations mentioned here that previously relied on static images in the old git repository, and linked them appropriately to their new Storyblok URLs (minus one person's page who we have removed for the time being). Everything seems to work perfectly fine on the site loading-wise, so if we are happy using that platform then I think we are all good here!

**Comment by garrettdashnelson** [comment]
Awesome! Closing this for now, then.
