### ISSUE TITLE
Updating map tags via CSV

### ISSUE THREAD

**Issue by almontg** [bplmaps/argo-astro#48]
Would love to have a way to bulk update maps via a csv. Right now, I have a bunch of new tagging and event data that roughly follows this model:

| commonwealth id | tag list|
|-----|-----|
|commonwealth:6t053n77m|Published; Hand Coloring, Surveys, Houses and Property, Borders, Roads and Routes, Cartouche, Animal| 

i.e., the key field is the commonwealth id and tags/events are in a comma separated list. Is this something that would be doable currently? We (by which I mean Henry) could probably alter our data to make the tag/event the key field insted if that better matches our data model here.

Being able to do this would make adding our current backlog of tags much easier rather than having to do it facet-by-facet or map-by-map as was the case in the old cms. 

I suspect that this would work best in tandem with creating separate files which act as the source of record for various tags which would then be called by ie the facets page (as I mentioned in the slack chat) but I defer to the web dev experts here ha

**Comment by almontg** [comment]
(should note that changing the tag names to a more formal persistent id from the current full name of the tag/event would be trival)

**Comment by garrettdashnelson** [comment]
@almontg This should be fairly straightforward. The thing that we'll need to address is that our themes now all follow a homologous two-level depth model and so we need to indicate what tags (i.e. facet-categories) go with what groups (i.e. facets).

I don't know how much of a lift this would be relative to how you have data stored on your side, but the _ideal_ CSV would look like this:

| commonwealth_id        | empires-and-nations | features          | languages | subjects         |
|------------------------|---------------------|-------------------|-----------|------------------|
| commonwealth:6t053n77m | french,british      | cartouche,printed | spanish   | borders,military |


and where each of the entries exactly followed the controlled vocabularies of identifiers in the JSON file—these are the same identifiers which compose the URL. For instance, https://argo-astro-dev.netlify.app/facets/features/non-map/ has top-level identifier `features` and second-level `non-map`.

**Comment by almontg** [comment]
@garrettdashnelson redoing the data in that way should be doable!

**Comment by almontg** [comment]
@garrettdashnelson working on cleaning up our data to fit with this but realized I don't have a list of commonwealth IDs for the newly ingested maps from Clements and LAC -- do we have a list of Clements/LAC IDs or titles keyed to commonwealth IDs?

**Comment by garrettdashnelson** [comment]
@almontg Just checking that you have what you need on this and are in progress of sending a sample CSV of new tags for Clements, etc.?

**Comment by almontg** [comment]
@garrettdashnelson I am! Will send over a sample CSV for Library and Archives Canada
