### ISSUE TITLE
Search page: add search button and pagination

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/argo-astro#59]
I've already created the bare bones of a functional search page at `/src/pages/search.astro`. It needs to be improved in the following ways:

1. Currently, it auto-searches as text is entered (debounced 600 ms). There should probably also be a "Search" button next to the text field for both accessibility and UI reasons, which would simply execute the search immediately without a debounce.

2. The JSON object returned by the search API exposes the following (example) which allow for pagination:

```"pages":{"current_page":1,"next_page":2,"prev_page":null,"total_pages":503,"limit_value":20,"offset_value":0,"total_count":10055,"first_page?":true,"last_page?":false}}}```

Subsequent pagination queries can be made by passing to the `page` query parameter of the fetch.

**Comment by hkemp2128** [comment]
I don't think this is an issue for milestone 3, but I do just want to raise the point that I think non-map site content (blog posts, people biographies, stories, and anything else we decide to add in the future) should also be searchable; if I make a site search for John Montresor, then I should get his biography page as an option alongside all the maps connected to him. I know this doesn't exist on the old site, so likely a future issue, but just wanted to put it on everyone's radar.
