### ISSUE TITLE
Clean up footer

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/argo-astro#60]
This is a question for the interpretive team @almontg @hkemp2128 @emilyrbowe. Right now the footer section feels pretty random to me, and I'm not sure it makes sense to have a hard-coded set of stories and themes in there. What do you think about the following?

1. Have "Recent Stories" always populated with the three most recently published stories
2. Second column could be: "Explore By" and the children are: "Themes", "People", and "Partner Collections"
3. "For Educators" gets rolled up under "About ARGO" until we have more content there.

**Comment by almontg** [comment]
This all sounds good to me -- agree it shouldn't be hard coded and your suggestions here make sense to me. I'll check in with Zerah about the current status of the education modules which were commissioned last year and see if we might be able to get them up for the relaunch

**Comment by garrettdashnelson** [comment]
@alexandergknoll I think this one should be straightforward—let me know if you have questions.
