### ISSUE TITLE
Decide what to do about the "Drawer" element

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/argo-astro#62]
We need to decide whether we want to retain a "Drawer" feature in the UI, and, if not, what we want to do instead in terms of how to display maps attached to each of the timeline events.

**Comment by almontg** [comment]
Strongly in favor of keeping the drawer element

**Comment by hkemp2128** [comment]
I second keeping the drawer element; I do want to bring up that on the old site, once the drawer was opened, there is no way to close out of it. You can minimize it, but it will stay at the bottom of the browser window until you click into a different page.

**Comment by alexandergknoll** [comment]
What about instead of a "drawer" this were implemented as a modal dialog, for example:

https://tailwindui.com/components/application-ui/overlays/dialogs

**Comment by almontg** [comment]
I'm not sure I like that idea; to me the strength of the drawer element is that it allows you to keep exploring the main page and changes based on what you are clicking into. I think a popup like this would be a bit jarring as it's a mode typically use to confirm/cancel an action rather than reveal more info, and would require you to react immediately before re-gaining access to the site.

**Comment by almontg** [comment]
Something more along these lines would work better I think, although I am very fond of how it worked originally: https://tailwindui.com/components/application-ui/overlays/slide-overs

**Comment by garrettdashnelson** [comment]
I think before we make any more progress on this, I would like to talk at our Monday meeting about it. While I agree that the original version was nifty, I think it was very inconsistently applied and we did not have a clear model moving forwards for how it would be implemented in the site outside of opening groups of collections objects from the timeline.

**Comment by garrettdashnelson** [comment]
@alexandergknoll We talked yesterday about this, and there is consensus that we can start using the TailwindUI "slide-over" element on the right side of the page ... and then, later on, if we decide we really want to force it to page bottom, we can look at that.

This component should be present on only the home page for now, and it should expose a prop with an array of `identifiers` that refer to collections objects. For now, the only component that will trigger it is the Timeline component, which already has a blank method called `openDrawer`.
