### ISSUE TITLE
Create a reusable client-side lazyloading collection record card component

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/argo-astro#7]
I've created a starter file for this at `src/components/CollectionCard.astro` which works in the most very basic sense.

This is the component that should be used to populate gallery grids (for instance, the collection record items associated with a Person page or on a Facet-category page). 

It can probably just take one prop like `identifier` which identifies a single record from the `src/content/maps` content collection.

In an ideal scenario, I'd like the image to lazyload only when the element enters the viewport.

**Comment by alexandergknoll** [comment]
I think we can use the Astro [client:visible directive](https://docs.astro.build/en/reference/directives-reference/#clientvisible) to handle this pretty easily.  I added it in PR #11 for us to test

**Comment by alexandergknoll** [comment]
Actually--after reading more I don't think that directive does what I thought it did. So forget my last message!
