### ISSUE TITLE
Fix numbering within Theme elements

### ISSUE THREAD

**Issue by hkemp2128** [bplmaps/argo-astro#70]
Noticed this yesterday; when you go into each Theme's page and are presented with all the subcategories, the numbering system seems to be adding each subcategory's count onto the total number instead of displaying their own individual counts. For example, under Features, the Cartouche tag says it has 528 entries when it actually only has 435; it seems to be adding 435 to the previous category's 93 total to get that new number. I assume this is an easy fix since it is displaying correctly on the homepage, just incorrect within each Theme page.

**Comment by alexandergknoll** [comment]
Great catch @hkemp2128 !  I've opened a PR that will resolve the issue
