### ISSUE TITLE
Tagging people bios

### ISSUE THREAD

**Issue by hkemp2128** [bplmaps/argo-astro#76]
Putting this as an issue largely as a reminder to myself; we still have a few people bios without tags that show "Untagged" at the top of the bios and are also listed in a separate "Untagged" drop-down menu option when browsing other bios, which is ugly and should be fixed by 2.0 rollout. I will go through and check the people without tags and update accordingly with Ala's approval (I'm no historian).

**Comment by almontg** [comment]
@garrettdashnelson this one's my fault -- I'll decide what to do with these today and make the updates.

**Comment by almontg** [comment]
Done
