### ISSUE TITLE
Final styling implementations

### ISSUE THREAD

**Issue by hkemp2128** [bplmaps/argo-astro#77]
Ala and I have gone over the site and noted 4 style implementations that we think should be done before launch; hoping they are all quick fixes, but let me know if you disagree with any of these or if you think they are infeasible for milestone 3.

1. URLs within people biographies:

These are currently presented just as underlined text within paragraphs; can we make it so that they show up blue/purple like standard URLs? I don't feel that it's obvious that they are clickable links as of right now. The old site has them as more of a deep blue shade, which would be fine; just something besides the underline to differentiate them from normal text.

2. Collection Grid background coloring

It's faint, but now that it's been pointed out to me I cannot unsee it. The white background box behind the titles of each collection grid is a slightly different color than the background of the site, so you can see the faint rectangle spreading all the way across the page at the top of each collection grid (on the homepage and within stories). This issue is not present on the old site, so am unsure what changed between the two, but we should make the background transparent for those, or matching the site background color.

3. Footnotes (also within people bios, and certain story pages)

We are not fans of the current display of the "return to place" arrows at the end of each footnote (for lack of a technical vocabulary term). The blue box is a little off-putting; wondering if we can implement styling to make them stand out a little less? I haven't been able to find much about changing footnote styles myself but am hoping it would be a relatively easy fix to change the blue background to just a transparent field across the whole site, rather than going into every page and implementing it individually.

4. Slider elements underneath the people bios

The slider containers at the end of the people biographies holding the related maps look a little wonky; the scroll arrows overlap with the map content presented within. Not sure if there is an easy fix here, but just wanted to raise a flag here in case you were not aware of it.

**Comment by almontg** [comment]
@garrettdashnelson Henry is out today and tomorrow on vacation; I'll do a quick review myself today but will wait until he's back to make the final call unless I see anything especially notable.

**Comment by hkemp2128** [comment]
@garrettdashnelson Just getting back into the office and seeing this; I think the only other thing that should be done before switchover is to change the URL coloring to blue/purple instead of black (this is a must for accessibility reasons in my opinion, otherwise text just appears to be underlined). The footnote styling I am fine to put off but I do think should be changed eventually if possible. Unless either of these have been implemented somewhere other than main and not yet merged, I don't see that they've been addressed yet.

**Comment by garrettdashnelson** [comment]
@hkemp2128 (cc @alexandergknoll), I tested out a solution for this on `content-staging`. It looks like this:  

<img width="752" alt="Screenshot 2024-03-13 at 2 18 32 PM" src="https://github.com/bplmaps/argo-astro/assets/2424901/24e87d71-4d5d-42ea-8b7a-e08f24e4aa1b">

**Comment by hkemp2128** [comment]
I think that looks great!

**Comment by almontg** [comment]
Agree!

**Comment by garrettdashnelson** [comment]
Closed by #96
