### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by alexandergknoll** [bplmaps/argo-astro#85]
Due to a couple of routes containing several hundred items, I would like to add pagination for the following routes using Astro's [native pagination functionality](https://docs.astro.build/en/guides/routing/#pagination).  Do you have any concerns with that approach @garrettdashnelson ?

- `/facets/[facet]/[category]`
- `/partner-collections/[identifier]`

**Comment by garrettdashnelson** [comment]
Sounds great—I was only avoiding this because I hadn't looked into Astro's pagination functionality. Looks quite straightforward so I would say go for it!

**Comment by garrettdashnelson** [comment]
Closed by #94
